export const SET_PERSON = 'SET_PERSON';

export const SET_NAME = 'SET_NAME';
export const CREATE_NAME = 'CREATE_NAME';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const SET_SENDING_MESSAGE = 'SET_SENDING_MESSAGE';
export const UNSET_SENDING_MESSAGE = 'UNSET_SENDING_MESSAGE';
